version: "3.8"

services:
  # MySQL 데이터베이스
  mysql:
    image: mysql:8.0
    container_name: profile-mysql
    restart: always
    environment:
      MYSQL_DATABASE: profiledb
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 백엔드 서비스
  backend:
    build: ./backend
    container_name: profile-backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/profiledb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=userpassword
    ports:
      - "8080:8080"

  # 프론트엔드 서비스
  frontend:
    build: ./frontend
    container_name: profile-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080

volumes:
  mysql-data:
